### ISSUE TITLE
Witherbark Bloodling can be looted

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#419]
**Describe Your Issue**
[Witherbark Broodguard](https://classic.wowhead.com/npc=2686/witherbark-broodguard), spiders in south Hinterlands, spawn two [Witherbark Bloodling](https://classic.wowhead.com/npc=7768/witherbark-bloodling) when they die. These Bloodlings die in one hit. On Hyjal they can also be looted, and they drop lots of trade goods.

**Steps To Reproduce**
``SELECT item_template.name, creature_template.name, creature_loot_template.ChanceOrQuestChance FROM item_template``
``INNER JOIN creature_loot_template ON creature_loot_template.item = item_template.entry``
``INNER JOIN creature_template ON creature_template.loot_id = creature_loot_template.entry``
``WHERE creature_template.name = 'Witherbark Bloodling'``
This should show you the drop table of these spiders, and you'll see they drop trade goods, mostly herbs.

1. You could also go to around 33,69 in Hinterlands.
2. Kill Witherbark Bloodguards, the spiders. Kill the Witherbark Bloodlings that spawn.
3. Observe that they can be looted, glittering.

**Expected Behaviour**
The Bloodlings should not drop anything. If you look on their [Wowhead Classic page](https://classic.wowhead.com/npc=7768/witherbark-bloodling#comments) you will see that no loot is listed. There's also a comment about how they don't drop anythng.

Furthermore, you can also watch [Joana's Vanilla Guide](https://youtu.be/wAFdoIStMZI?t=11980), at 3:19:40 where he begins fighting these spiders. At 3:20:06, 3:26:20 and 3:33:00 you can see they are not glittering.

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1097

**Comment by Simp-N** [comment]
I'd like to point out that this bug still lingers. They can still be looted.
![Sorted_WoWScrnShot_210426_013713](https://user-images.githubusercontent.com/75734743/116225686-6d6dc780-a752-11eb-94c8-6eaed655ba07.png)

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1142
