### ISSUE TITLE
Rogue talent Ruthlessness not procing AT ALL (edit)

### ISSUE THREAD

**Issue by Barwaat** [the-hyjal-project/bugtracker#492]
**Describe Your Issue**
While inside MC the rogue talent Ruthlessness is not proccing, when you use a finisher move on an enemy there's a 60% chance (with 3/3) to add a combo point to the enemy, but while zoned inside MC, it's not working (asked other rogues and it never does).
Edit : the issue is now global, this talent doesn't work at all, anywhere.

**Steps To Reproduce**
Go into MC as a rogue and use finisher moves, you will never get a combo point after while you have ruthlessness.
Edit : reproductible everywhere.

Spell: https://classic.wowhead.com/spell=14161

**Expected Behaviour**
It procs in other instances and in open world, it should work in MC too !

**Comment by ratkosrb** [comment]
I know why this happens. There is a hacky fix for this talent in the core, cause it actually can't work without batching, and now that batching of procs is implemented, that hack breaks the proper way the talent should function.

**Comment by Barwaat** [comment]
oh cool, a fix would be available when ?

Thanks alot for the quick response !

**Comment by ratkosrb** [comment]
Fixed here - https://github.com/vmangos/core/commit/ab61aacc5c02fe3961df8f619c9812768851ce0e

**Comment by Saprape** [comment]
This talent still doesn't work in open world. I have 2 points in it (40%) and finishing moves do not add a combo point to a target. Just NEVER. This talent worked well adout a week ago.

**Comment by Nolin7777** [comment]
There is no point to comment on a fixed and closed ticket. This fix already applied but not 9n the realm yet, because it would need a restart.

**Comment by Saprape** [comment]
so restart it, what are you waiting for - death?
