### ISSUE TITLE
The escort quest Supplies to Auberdine has similar issues as some other escort quests. 

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#71]
The escort quest Supplies to Auberdine has similar issues as some other escort quests. Firstly, enemies don't attack Feero Ironhand. Secondly, the range at which the quest fails because you got too far away from him seems too long. I died twice during the quest, ran quite far away from Ironhand at one point and I was still able to finish it. Lastly, the mobs which spawn during the escort automatically aggro onto you even if you are in stealth similarly to the escort quest The Absent Minded Prospector. Feero Ironhand is also missing some RP text.

Steps To Reproduce

1. Start the quest.
(2.) At some point during the quest, put some distance between him and you to see how long the quest fail radius is.
3. Get in stealth before the first wave of mobs.
4. Notice how the mobs automatically aggro onto you and ignore Feero Ironhand.
5. Use vanish and notice how the mobs still ignore him and eventually despawn, except if he attacked a mob it'll keep evading until you kill it.
6. Notice how after killing all the mobs in the wave, Ironhand doesn't say any RP text. He's also missing a bit of RP text right as the last wave spawns.
7. Repeat step 6 for the two remaining waves to notice the missing RP text.
https://classic.wowhead.com/quest=976/supplies-to-auberdine
https://classic.wowhead.com/npc=4484/feero-ironhand

Expected Behavior

Enemies should attack Ironhand, the quest fail radius should be smaller, mobs shouldn't automatically aggro onto you if you are in stealth (not 100% sure about this) and he should say some RP text after each wave and right as the last wave spawns. Here's a timestamped link of the quest from Classic WoW: https://youtu.be/6_GRXePh8vw?t=7421. Check 2:05:36, 2:07:10, 2:08:34 and 2:09:17 in the video for the missing RP texts.
<!--- Include IDs of affected NPCs , items, quests or spells with a link to the relevant page.

**Comment by ratkosrb** [comment]
Aggro issue fixed here https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db

**Comment by petage** [comment]
@Nolin7777 This issue should be reopened, since only the aggro issue has been fixed. The escort quest is still missing some RP text as mentioned in the description. I haven't found evidence regarding the quest fail radius or the mobs aggroing you in stealth, so those issues can be ignored.
